<!DOCTYPE HTML>
<html>

	<head>

		<title>Dodaj</title>

		<meta charset="utf-8">

	</head>

	<body>

		<form action="<?php echo $_SERVER['REQUEST_URI'];?>" method="post">
			<label>Nazwa tabeli: <input type="text" name="table"></label><br>
			<table>
				<thead>
					<tr>
						<td>Nazwa</td>
						<td>Typ</td>
						<td>Długosć/Wartosci</td>
						<td>Ustawienia domyslne</td>
						<td>Metoda porównywania napisów</td>
						<td>Atrybuty</td>
						<td>Null</td>
						<td>Indekx</td>
						<td>Auto increment</td>
					</tr>
				</thead>
				<tbody>
					<tr>
					
					</tr>
				</tbody>
			</table>
			<input type="submit" value="add">
		</form>
	
	</body>

</html>