<!DOCTYPE HTML>
<html>

	<head>
	
        <title><?php echo $this->title; ?></title>
		<meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="/main.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <style>
            table{
                margin: 4px;
            }
            
            tr:nth-child(1){
                background-color: #3299CC;
                text-align: center;
            }
            
            td{
                padding: 10px;
            }
            
            tr:nth-child(even){
                background-color: #f2f2f2;
            }
        </style>
	</head>

	<body>
	
		<table>
			<tr>
			     <?php foreach ($this->description as $value) { ?>
				    <td><?php echo $value; ?></td>
			     <?php }; ?>
			</tr>
			     <?php foreach ($this->rows as $row) { ?>
			<tr>
				<?php foreach ($row as $field) { ?>
				<td><?php echo $field; ?></td>
				<?php }; ?>
			</tr>
			     <?php }; ?>
		</table>
	
	</body>

</html>