<!DOCTYPE HTML>
<html>

	<head>
	
        <title><?php echo $this->title; ?></title>
		<meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="/main.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <style>
            .nav{
                height: calc(100% - 60px);
            }
            
            .left_panel{
                width: 300px;
                height: 100%;
                float: left;
            }
            
            .add{
                width: calc(100% - 20px);
                height: calc(60px - 22px);
                background-color: #1f1f1f;
                border-top: 2px solid #3299cc;
                padding: 10px;
                clear: both;
            }
            
            input{
                width: 200px;
                height: 38px;
                border: 0px;
                background-color: #dfdfdf;
                font-size: 22px;
                float: left;
            }
            
            #submit{
                width: 38px;
                height: 38px;
                background-color: #666;
                float: left;
            }
            
        </style>
	</head>

	<body>
        
        <div class="left_panel">
            
            <div class="nav">
                <h1>MyDatabase</h1>
                <ul>
                    <li><h3>Bazy danych:</h3></li>
                    <?php foreach ($this->databases as $database) { ?>
                    <li><a href="/database/show/<?php echo $database; ?>"><?php echo $database; ?></a></li>
                    <?php }; ?>
                </ul>
                </div>
                
                <div class="add">
                    <form action="/database/add" method="post">
                        <input type="text" name="database" placeholder="Dodaj bazę">
                        <input id="submit" type="submit" value="+">
                    </form>
                </div>
        </div>
        <div class="conent">
            <div class="options">
              
            </div>
        </div>
        
	</body>

</html>