<!DOCTYPE HTML>
<html>
	
	<head>
	
		<title>tytul</title>
		
		<meta charset="utf-8">
	
	</head>
	<body>
		<?php if (!$this->create) { ?>
			<?php if (!!$this->reason) {?>
				<p><?php echo $this->reason; ?></p>
			<?php } else { ?>
				<script>
                    alert("Podaj poprawną nazwe");
                </script>
			<?php } ?>
		<?php } else { ?>
		<script>
            alert("Baza została utworzona");
        </script>
		<?php 
			header("Location: http://" . $_SERVER['HTTP_HOST'] . "/database/show/" . $this->name);
		} ?>
    </body>
</html>
